[workspace]
members = [
    "crates/derive",
    "crates/hlbc",
    "crates/decompiler",
    "crates/cli",
    "crates/gui"
]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 4

[profile.release-web]
inherits = "release"
opt-level = "s"
