[package]
name = "hlbc-cli"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Hashlink bytecode disassembler and analyzer"
authors = ["Guillaume Anthouard <25181283+Gui-Yom@users.noreply.github.com>"]
repository = "https://github.com/Gui-Yom/hlbc"
keywords = ["hashlink", "bytecode", "disassembler", "analysis"]
categories = ["command-line-utilities", "parsing", "visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hlbc = { version = "0.1", path = ".." }
termcolor = "1"
anyhow = "1"
atty = "0.2"

[features]
default = []
graph = ["hlbc/graph"]
