[package]
name = "hlbc-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hlbc = { version = "0.1.0", path = ".." }
termcolor = "1"
anyhow = "1"
atty = "0.2"

[features]
default = []
graph = ["hlbc/graph"]
