[package]
name = "hlbc-indexing"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hlbc = { version = "0.7", path = "../hlbc" }
tantivy = "0.19"
