name: Deploy GUI to GitHub Pages

on:
  push:
    tags:
      - "gui-v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v2

      - uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: 'latest'

      - name: Install wasm-opt
        run: wget -qO- https://github.com/WebAssembly/binaryen/releases/download/version_112/binaryen-version_112-x86_64-linux.tar.gz | tar xvz -C /home/runner/.cargo/bin/ binaryen-version_112/bin/wasm-opt --strip=2

      - name: Build
        working-directory: hlbc-gui/web
        run: sh build.sh

      - name: Upload artifact 🚀
        uses: actions/upload-pages-artifact@v1
        with:
          path: hlbc-gui/web/dist/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v2
